# Generated by Django 4.2.1 on 2023-09-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0001_initial'),
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_Compose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('recipients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobListings.applicant')),
            ],
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
