# Generated by Django 4.2.1 on 2023-09-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0003_email_compose_send_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email_compose',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
