# Generated by Django 4.2.1 on 2023-09-14 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='currntly_accepting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='description_file',
            field=models.FileField(default=datetime.datetime(2023, 9, 14, 15, 23, 55, 611644, tzinfo=datetime.timezone.utc), upload_to='static/jd/'),
            preserve_default=False,
        ),
    ]
