# Generated by Django 4.2.1 on 2023-09-14 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0002_joblisting_currntly_accepting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='currntly_accepting',
            new_name='currently_accepting',
        ),
    ]
