# Generated by Django 4.2.1 on 2023-09-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0003_rename_currntly_accepting_joblisting_currently_accepting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='currently_accepting',
            new_name='currently_accpting',
        ),
    ]
