# Generated by Django 4.2.1 on 2023-09-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobListings', '0004_rename_currently_accepting_joblisting_currently_accpting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblisting',
            old_name='currently_accpting',
            new_name='currently_accepting',
        ),
    ]
